name: pps-msibi
channels:
  - conda-forge
dependencies:
  - flowermd >= 1.2.0
  - freud = 2.13.2
  - signac = 2.1.0
  - signac-flow = 0.26.1
  - cuda-version = 11.8
  - more-itertools
  - jupyter
  - pip:
      - git+https://github.com/cmelab/msibi
